Feature/design add taks
deyvisnvg/todoApp pull request #2
Opened 2023-10-13 23:01 UTC by deyvisnvg

# Diseño Agregar Tareas - TODO APP
Se ha implementado un pequeño diseño para el boton agregar tareas de nuestro TODO APP

2023-10-17 22:23 UTC, linder3hs requested changes

2023-10-17 22:23 UTC, linder3hs commented on src/App.jsx
> +      <div className='p-6 h-screen'>
@deyvisnvg te recomiendo que esto sea un componente puedes llamarlo `Header`

2023-10-17 22:23 UTC, linder3hs commented on src/App.jsx
> +        <div className='flex justify-center'>
Esto también puede ser un componente

2023-10-27 23:19 UTC, deyvisnvg reviewed
# Recomendaciones Implementadas - TODO APP
- Se ha implementado el componente para el Botton.
- Se ha implementado el componente para el Footer (Diseño de Agregar Tareas).
- Se ha implementado el componente para el diseño de la cabecera.

2023-12-13 20:37 UTC, merged